// 產業關鍵字模板系統
// 每個產業 48 個關鍵字，分 4 類：service / tech / env / price

export type TemplateCategory = 'service' | 'tech' | 'env' | 'price';

// DB keyword_category enum: 'general' | 'product' | 'service' | 'location' | 'experience'
// Map template category -> DB keyword_category
export const TEMPLATE_CATEGORY_MAP: Record<TemplateCategory, 'service' | 'general' | 'experience' | 'product' | 'location'> = {
  service: 'service',
  tech: 'product',
  env: 'experience',  // DB uses 'experience', not 'environment'
  price: 'general',
};

export const TEMPLATE_CATEGORY_LABELS: Record<TemplateCategory, string> = {
  service: '服務溝通',
  tech: '技術成效',
  env: '環境設備',
  price: '價格相關',
};

export interface TemplateKeyword {
  keyword: string;
  category: TemplateCategory;
}

export interface IndustryTemplate {
  id: string;
  label: string;
  emoji: string;
  keywords: TemplateKeyword[];
}

export const INDUSTRY_TEMPLATES: IndustryTemplate[] = [
  {
    id: 'optical',
    label: '眼鏡業',
    emoji: '👓',
    keywords: [
      // service (12)
      { keyword: '驗光很仔細', category: 'service' },
      { keyword: '解說很清楚', category: 'service' },
      { keyword: '不強迫推銷', category: 'service' },
      { keyword: '態度親切自然', category: 'service' },
      { keyword: '耐心解答疑問', category: 'service' },
      { keyword: '配鏡建議好', category: 'service' },
      { keyword: '取鏡速度快', category: 'service' },
      { keyword: '售後服務好', category: 'service' },
      { keyword: '調整很細心', category: 'service' },
      { keyword: '預約不用等', category: 'service' },
      { keyword: '幫助選合適框', category: 'service' },
      { keyword: '說明副作用', category: 'service' },
      // tech (12)
      { keyword: '驗光精準', category: 'tech' },
      { keyword: '鏡片品質好', category: 'tech' },
      { keyword: '配鏡精準度高', category: 'tech' },
      { keyword: '設備很現代', category: 'tech' },
      { keyword: '鏡框款式多', category: 'tech' },
      { keyword: '漸進片技術好', category: 'tech' },
      { keyword: '隱形眼鏡齊全', category: 'tech' },
      { keyword: '鏡架品牌多', category: 'tech' },
      { keyword: '鍍膜品質佳', category: 'tech' },
      { keyword: '視力改善明顯', category: 'tech' },
      { keyword: '眼壓量測準確', category: 'tech' },
      { keyword: '電腦驗光設備新', category: 'tech' },
      // env (12)
      { keyword: '環境整潔舒適', category: 'env' },
      { keyword: '燈光充足明亮', category: 'env' },
      { keyword: '展示區寬敞', category: 'env' },
      { keyword: '停車很方便', category: 'env' },
      { keyword: '鄰近大眾運輸', category: 'env' },
      { keyword: '試戴區舒服', category: 'env' },
      { keyword: '候診座位充足', category: 'env' },
      { keyword: '鏡框陳列清晰', category: 'env' },
      { keyword: '空調舒適', category: 'env' },
      { keyword: '無障礙空間', category: 'env' },
      { keyword: '整體視覺清爽', category: 'env' },
      { keyword: '消毒設備完善', category: 'env' },
      // price (12)
      { keyword: '價格透明合理', category: 'price' },
      { keyword: '不亂加收費用', category: 'price' },
      { keyword: '有各種價位', category: 'price' },
      { keyword: '配套優惠划算', category: 'price' },
      { keyword: '性價比超高', category: 'price' },
      { keyword: '學生優惠好', category: 'price' },
      { keyword: '換片費用合理', category: 'price' },
      { keyword: '配鏡附加服務多', category: 'price' },
      { keyword: '免費調整鼻墊', category: 'price' },
      { keyword: '保固條件清楚', category: 'price' },
      { keyword: '保險可搭配', category: 'price' },
      { keyword: '收費說明清晰', category: 'price' },
    ],
  },
  {
    id: 'dental',
    label: '牙醫診所',
    emoji: '🦷',
    keywords: [
      // service (12)
      { keyword: '麻醉不痛', category: 'service' },
      { keyword: '解釋每個步驟', category: 'service' },
      { keyword: '預約準時不等待', category: 'service' },
      { keyword: '護理師親切', category: 'service' },
      { keyword: '不強迫推銷', category: 'service' },
      { keyword: '看診不趕時間', category: 'service' },
      { keyword: '術後追蹤用心', category: 'service' },
      { keyword: '小孩不害怕', category: 'service' },
      { keyword: '洗牙很仔細', category: 'service' },
      { keyword: '說明很詳細', category: 'service' },
      { keyword: '問診很耐心', category: 'service' },
      { keyword: '回診提醒貼心', category: 'service' },
      // tech (12)
      { keyword: '醫師經驗豐富', category: 'tech' },
      { keyword: '器械全程消毒', category: 'tech' },
      { keyword: '設備很新穎', category: 'tech' },
      { keyword: '技術值得信賴', category: 'tech' },
      { keyword: '根管精準', category: 'tech' },
      { keyword: '植牙技術好', category: 'tech' },
      { keyword: '矯正進度穩', category: 'tech' },
      { keyword: '補牙很密合', category: 'tech' },
      { keyword: 'X光設備齊全', category: 'tech' },
      { keyword: '數位印模精準', category: 'tech' },
      { keyword: '美白效果明顯', category: 'tech' },
      { keyword: '義齒製作精良', category: 'tech' },
      // env (12)
      { keyword: '環境乾淨放鬆', category: 'env' },
      { keyword: '候診不無聊', category: 'env' },
      { keyword: '停車很方便', category: 'env' },
      { keyword: '空間寬敞舒適', category: 'env' },
      { keyword: '消毒流程嚴謹', category: 'env' },
      { keyword: '診間隔音好', category: 'env' },
      { keyword: '有兒童候診區', category: 'env' },
      { keyword: '整體設計溫和', category: 'env' },
      { keyword: '院內空氣清新', category: 'env' },
      { keyword: '洗手間很清潔', category: 'env' },
      { keyword: '燈光柔和舒適', category: 'env' },
      { keyword: '地點交通便利', category: 'env' },
      // price (12)
      { keyword: '收費透明合理', category: 'price' },
      { keyword: '健保申報正確', category: 'price' },
      { keyword: '自費說明清楚', category: 'price' },
      { keyword: '不亂加收費', category: 'price' },
      { keyword: '各項費用明細', category: 'price' },
      { keyword: '矯正費用合理', category: 'price' },
      { keyword: '植牙性價比高', category: 'price' },
      { keyword: '分期付款彈性', category: 'price' },
      { keyword: '健保自費分清', category: 'price' },
      { keyword: '治療前告知費用', category: 'price' },
      { keyword: '洗牙費用公道', category: 'price' },
      { keyword: '不推銷不必要項目', category: 'price' },
    ],
  },
  {
    id: 'hair_salon',
    label: '美髮沙龍',
    emoji: '💇',
    keywords: [
      // service (12)
      { keyword: '設計師溝通好', category: 'service' },
      { keyword: '不推銷產品', category: 'service' },
      { keyword: '耐心聽需求', category: 'service' },
      { keyword: '預約不用等', category: 'service' },
      { keyword: '洗頭很舒服', category: 'service' },
      { keyword: '態度親切自然', category: 'service' },
      { keyword: '頭皮按摩放鬆', category: 'service' },
      { keyword: '顧客服務細膩', category: 'service' },
      { keyword: '造型師資歷深', category: 'service' },
      { keyword: '施術說明清楚', category: 'service' },
      { keyword: '準時完成', category: 'service' },
      { keyword: '售後追蹤貼心', category: 'service' },
      // tech (12)
      { keyword: '剪髮技術好', category: 'tech' },
      { keyword: '燙髮效果自然', category: 'tech' },
      { keyword: '染髮顏色持久', category: 'tech' },
      { keyword: '造型很滿意', category: 'tech' },
      { keyword: '頭皮護理專業', category: 'tech' },
      { keyword: '髮質變好了', category: 'tech' },
      { keyword: '燙捲均勻自然', category: 'tech' },
      { keyword: '離子燙技術好', category: 'tech' },
      { keyword: '染後色澤均勻', category: 'tech' },
      { keyword: '燙後彈性佳', category: 'tech' },
      { keyword: '修剪層次感好', category: 'tech' },
      { keyword: '護髮效果顯著', category: 'tech' },
      // env (12)
      { keyword: '環境時尚舒適', category: 'env' },
      { keyword: '空間很舒適', category: 'env' },
      { keyword: '停車很方便', category: 'env' },
      { keyword: '燈光設計質感', category: 'env' },
      { keyword: '藥水味道不重', category: 'env' },
      { keyword: '座椅舒適好坐', category: 'env' },
      { keyword: '整體清潔衛生', category: 'env' },
      { keyword: '有無線網路', category: 'env' },
      { keyword: '提供飲品', category: 'env' },
      { keyword: '雜誌閱讀豐富', category: 'env' },
      { keyword: '音樂氛圍好', category: 'env' },
      { keyword: '院內採光充足', category: 'env' },
      // price (12)
      { keyword: '價格透明', category: 'price' },
      { keyword: '不亂追加費用', category: 'price' },
      { keyword: '性價比超高', category: 'price' },
      { keyword: '收費前告知', category: 'price' },
      { keyword: '辦卡划算', category: 'price' },
      { keyword: '學生友善', category: 'price' },
      { keyword: '護髮加價合理', category: 'price' },
      { keyword: '提供套餐優惠', category: 'price' },
      { keyword: '洗剪燙超值', category: 'price' },
      { keyword: '染髮費用合理', category: 'price' },
      { keyword: '新客優惠', category: 'price' },
      { keyword: '費用明細清楚', category: 'price' },
    ],
  },
  {
    id: 'auto_service',
    label: '汽車保養',
    emoji: '🔧',
    keywords: [
      // service (12)
      { keyword: '師傅說明專業', category: 'service' },
      { keyword: '不強迫換件', category: 'service' },
      { keyword: '售後追蹤貼心', category: 'service' },
      { keyword: '接待態度好', category: 'service' },
      { keyword: '交車準時', category: 'service' },
      { keyword: '提供代步車', category: 'service' },
      { keyword: '維修前告知費用', category: 'service' },
      { keyword: '回廠很安心', category: 'service' },
      { keyword: '詳細說明狀況', category: 'service' },
      { keyword: '電話溝通清楚', category: 'service' },
      { keyword: '問題說明易懂', category: 'service' },
      { keyword: '保固有誠意', category: 'service' },
      // tech (12)
      { keyword: '技術值得信賴', category: 'tech' },
      { keyword: '保養效率高', category: 'tech' },
      { keyword: '維修品質穩定', category: 'tech' },
      { keyword: '洗車很仔細', category: 'tech' },
      { keyword: '底盤檢查詳細', category: 'tech' },
      { keyword: '快速找出問題', category: 'tech' },
      { keyword: '原廠零件正品', category: 'tech' },
      { keyword: '引擎問題精準', category: 'tech' },
      { keyword: '電瓶檢測完整', category: 'tech' },
      { keyword: '煞車維修紮實', category: 'tech' },
      { keyword: '空調清洗徹底', category: 'tech' },
      { keyword: '跑合試車確認', category: 'tech' },
      // env (12)
      { keyword: '環境整潔明亮', category: 'env' },
      { keyword: '休息區舒適', category: 'env' },
      { keyword: '停車很方便', category: 'env' },
      { keyword: '廠區寬敞整齊', category: 'env' },
      { keyword: '客廳有冷氣', category: 'env' },
      { keyword: '提供飲品點心', category: 'env' },
      { keyword: '有無線網路', category: 'env' },
      { keyword: '施工區透明', category: 'env' },
      { keyword: '等候區有電視', category: 'env' },
      { keyword: '廁所乾淨', category: 'env' },
      { keyword: '廠區燈光充足', category: 'env' },
      { keyword: '地點交通便利', category: 'env' },
      // price (12)
      { keyword: '價格公道透明', category: 'price' },
      { keyword: '零件不亂加價', category: 'price' },
      { keyword: '報價前告知', category: 'price' },
      { keyword: '工料分開說明', category: 'price' },
      { keyword: '不亂推銷耗材', category: 'price' },
      { keyword: '保養費用合理', category: 'price' },
      { keyword: '性價比很高', category: 'price' },
      { keyword: '定期保養優惠', category: 'price' },
      { keyword: '儲值卡划算', category: 'price' },
      { keyword: '費用明細完整', category: 'price' },
      { keyword: '無隱藏費用', category: 'price' },
      { keyword: '保固費用合理', category: 'price' },
    ],
  },
  {
    id: 'pet_hospital',
    label: '寵物醫院',
    emoji: '🐾',
    keywords: [
      // service (12)
      { keyword: '對貓狗很耐心', category: 'service' },
      { keyword: '解釋病因易懂', category: 'service' },
      { keyword: '不讓寵物緊張', category: 'service' },
      { keyword: '護理師很細心', category: 'service' },
      { keyword: '急診反應快速', category: 'service' },
      { keyword: '醫生溫柔', category: 'service' },
      { keyword: '追蹤回診貼心', category: 'service' },
      { keyword: '提供寵物零食', category: 'service' },
      { keyword: '術後照顧完善', category: 'service' },
      { keyword: '回院關懷通知', category: 'service' },
      { keyword: '候診安撫有方', category: 'service' },
      { keyword: '飼主溝通清楚', category: 'service' },
      // tech (12)
      { keyword: '診斷非常詳細', category: 'tech' },
      { keyword: '用藥很謹慎', category: 'tech' },
      { keyword: '手術經驗豐富', category: 'tech' },
      { keyword: '檢查項目完整', category: 'tech' },
      { keyword: '血液檢查準確', category: 'tech' },
      { keyword: '超音波設備新', category: 'tech' },
      { keyword: '麻醉管理嚴謹', category: 'tech' },
      { keyword: '術後康復快', category: 'tech' },
      { keyword: '皮膚問題精準', category: 'tech' },
      { keyword: '牙科設備完善', category: 'tech' },
      { keyword: '疫苗接種正確', category: 'tech' },
      { keyword: '影像判讀精準', category: 'tech' },
      // env (12)
      { keyword: '環境乾淨無異味', category: 'env' },
      { keyword: '候診空間舒適', category: 'env' },
      { keyword: '停車很方便', category: 'env' },
      { keyword: '貓狗候診分區', category: 'env' },
      { keyword: '消毒流程嚴格', category: 'env' },
      { keyword: '手術室設備齊全', category: 'env' },
      { keyword: '住院區空間大', category: 'env' },
      { keyword: '院內通風良好', category: 'env' },
      { keyword: '整體氛圍溫和', category: 'env' },
      { keyword: '前台整潔友善', category: 'env' },
      { keyword: '有觀察窗安心', category: 'env' },
      { keyword: '設備現代化', category: 'env' },
      // price (12)
      { keyword: '收費合理清楚', category: 'price' },
      { keyword: '診療前告知費用', category: 'price' },
      { keyword: '不亂推銷檢查', category: 'price' },
      { keyword: '費用明細完整', category: 'price' },
      { keyword: '手術費用合理', category: 'price' },
      { keyword: '藥費不暴利', category: 'price' },
      { keyword: '分期彈性付款', category: 'price' },
      { keyword: '寵物保險可用', category: 'price' },
      { keyword: '健診套餐划算', category: 'price' },
      { keyword: '疫苗費用合理', category: 'price' },
      { keyword: '性價比高', category: 'price' },
      { keyword: '沒有隱藏費用', category: 'price' },
    ],
  },
  {
    id: 'temple',
    label: '宗教宮廟',
    emoji: '⛩️',
    keywords: [
      // service (12)
      { keyword: '解籤非常詳細', category: 'service' },
      { keyword: '師兄姐很親切', category: 'service' },
      { keyword: '點燈流程清楚', category: 'service' },
      { keyword: '辦事準確靈驗', category: 'service' },
      { keyword: '祭祀指引細心', category: 'service' },
      { keyword: '隨喜不強迫', category: 'service' },
      { keyword: '問事回覆詳盡', category: 'service' },
      { keyword: '引導參拜有序', category: 'service' },
      { keyword: '安太歲很順利', category: 'service' },
      { keyword: '服務態度親和', category: 'service' },
      { keyword: '志工很熱心', category: 'service' },
      { keyword: '外地人也很照顧', category: 'service' },
      // tech (12)
      { keyword: '求財很靈驗', category: 'tech' },
      { keyword: '求平安很順利', category: 'tech' },
      { keyword: '非常有神威', category: 'tech' },
      { keyword: '指點迷津', category: 'tech' },
      { keyword: '籤詩解讀精準', category: 'tech' },
      { keyword: '法會儀式莊嚴', category: 'tech' },
      { keyword: '神明很靈感', category: 'tech' },
      { keyword: '擲筊有回應', category: 'tech' },
      { keyword: '收驚很有效', category: 'tech' },
      { keyword: '補運效果明顯', category: 'tech' },
      { keyword: '祈福儀式完整', category: 'tech' },
      { keyword: '文化傳承用心', category: 'tech' },
      // env (12)
      { keyword: '建築雕刻精美', category: 'env' },
      { keyword: '環境清靜莊嚴', category: 'env' },
      { keyword: '停車場很大', category: 'env' },
      { keyword: '洗手間乾淨', category: 'env' },
      { keyword: '香火鼎盛不嗆鼻', category: 'env' },
      { keyword: '動線規劃好', category: 'env' },
      { keyword: '古色古香', category: 'env' },
      { keyword: '庭園造景優美', category: 'env' },
      { keyword: '夜間燈光莊嚴', category: 'env' },
      { keyword: '廟埕空間寬敞', category: 'env' },
      { keyword: '周邊小吃豐富', category: 'env' },
      { keyword: '交通便利好找', category: 'env' },
      // price (12)
      { keyword: '收費透明', category: 'price' },
      { keyword: '點燈費用合理', category: 'price' },
      { keyword: '隨喜功德自由', category: 'price' },
      { keyword: '安太歲費公道', category: 'price' },
      { keyword: '法會費用透明', category: 'price' },
      { keyword: '金紙種類齊全', category: 'price' },
      { keyword: '不強迫添油香', category: 'price' },
      { keyword: '光明燈價格親民', category: 'price' },
      { keyword: '每年法會必參加', category: 'price' },
      { keyword: '心靈寄託中心', category: 'price' },
      { keyword: '拜完心情變好', category: 'price' },
      { keyword: '在地信仰依靠', category: 'price' },
    ],
  },
  {
    id: 'association',
    label: '社團法人/協會',
    emoji: '🤝',
    keywords: [
      // service (12)
      { keyword: '辦訓課程專業', category: 'service' },
      { keyword: '對接資源快速', category: 'service' },
      { keyword: '法律諮詢到位', category: 'service' },
      { keyword: '會務處理細心', category: 'service' },
      { keyword: '專家經驗豐富', category: 'service' },
      { keyword: '資料整理齊全', category: 'service' },
      { keyword: '服務效率極高', category: 'service' },
      { keyword: '提供實質幫助', category: 'service' },
      { keyword: '回覆速度很快', category: 'service' },
      { keyword: '行政作業順暢', category: 'service' },
      { keyword: '理事長很親民', category: 'service' },
      { keyword: '秘書處很用心', category: 'service' },
      // tech (12)
      { keyword: '入會受益匪淺', category: 'tech' },
      { keyword: '認識優秀夥伴', category: 'tech' },
      { keyword: '真正有在做事', category: 'tech' },
      { keyword: '產業資訊豐富', category: 'tech' },
      { keyword: '課程內容紮實', category: 'tech' },
      { keyword: '講師陣容堅強', category: 'tech' },
      { keyword: '輔導計畫完善', category: 'tech' },
      { keyword: '媒合機會多', category: 'tech' },
      { keyword: '認證制度公正', category: 'tech' },
      { keyword: '政策倡議有力', category: 'tech' },
      { keyword: '研討會品質高', category: 'tech' },
      { keyword: '跨業交流廣泛', category: 'tech' },
      // env (12)
      { keyword: '活動空間寬敞', category: 'env' },
      { keyword: '教室設備先進', category: 'env' },
      { keyword: '交通便利好找', category: 'env' },
      { keyword: '環境整潔舒適', category: 'env' },
      { keyword: '線上系統好用', category: 'env' },
      { keyword: '會議室設備齊全', category: 'env' },
      { keyword: '報名流程簡便', category: 'env' },
      { keyword: '場地燈光舒適', category: 'env' },
      { keyword: '茶水供應充足', category: 'env' },
      { keyword: '簽到系統便捷', category: 'env' },
      { keyword: '停車空間足夠', category: 'env' },
      { keyword: '無障礙設施完善', category: 'env' },
      // price (12)
      { keyword: '經費運用透明', category: 'price' },
      { keyword: '會費合理值得', category: 'price' },
      { keyword: '課程費用公道', category: 'price' },
      { keyword: '年費性價比高', category: 'price' },
      { keyword: '財務報告公開', category: 'price' },
      { keyword: '補助申請順利', category: 'price' },
      { keyword: '活動費用合理', category: 'price' },
      { keyword: '推薦同業加入', category: 'price' },
      { keyword: '像一個大家庭', category: 'price' },
      { keyword: '感受到溫暖', category: 'price' },
      { keyword: '很有歸屬感', category: 'price' },
      { keyword: '收費說明清楚', category: 'price' },
    ],
  },
];

// Helper: get template by id
export const getTemplateById = (id: string): IndustryTemplate | undefined =>
  INDUSTRY_TEMPLATES.find(t => t.id === id);

// Sandbox check (single source of truth)
export const SANDBOX_EMAIL = 'tornadolee20@yahoo.com.tw';
export const isSandboxMode = (email: string | null | undefined): boolean =>
  email?.toLowerCase() === SANDBOX_EMAIL.toLowerCase();
