// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wfaqnahahygtieyjnlji.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndmYXFuYWhhaHlndGlleWpubGppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NTU0NDUsImV4cCI6MjA3MDAzMTQ0NX0.0LuFBd95M0Wge9Oj6jfWAsNTd5FFEh1Tj52t0NtnQBo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

export async function testSupabaseConnection(): Promise<boolean> {
  try {
    const { error } = await supabase.from('stores').select('id').limit(1);
    return !error;
  } catch {
    return false;
  }
}