INSERT INTO industry_templates (template_id, label, emoji, keywords, sort_order, is_active) VALUES
('temple', '宗教宮廟', '⛩️', '[
  {"keyword":"解籤非常詳細","category":"service"},{"keyword":"師兄姐很親切","category":"service"},{"keyword":"點燈流程清楚","category":"service"},{"keyword":"辦事準確靈驗","category":"service"},{"keyword":"祭祀指引細心","category":"service"},{"keyword":"隨喜不強迫","category":"service"},{"keyword":"問事回覆詳盡","category":"service"},{"keyword":"引導參拜有序","category":"service"},{"keyword":"安太歲很順利","category":"service"},{"keyword":"服務態度親和","category":"service"},{"keyword":"志工很熱心","category":"service"},{"keyword":"外地人也很照顧","category":"service"},
  {"keyword":"求財很靈驗","category":"tech"},{"keyword":"求平安很順利","category":"tech"},{"keyword":"非常有神威","category":"tech"},{"keyword":"指點迷津","category":"tech"},{"keyword":"籤詩解讀精準","category":"tech"},{"keyword":"法會儀式莊嚴","category":"tech"},{"keyword":"神明很靈感","category":"tech"},{"keyword":"擲筊有回應","category":"tech"},{"keyword":"收驚很有效","category":"tech"},{"keyword":"補運效果明顯","category":"tech"},{"keyword":"祈福儀式完整","category":"tech"},{"keyword":"文化傳承用心","category":"tech"},
  {"keyword":"建築雕刻精美","category":"env"},{"keyword":"環境清靜莊嚴","category":"env"},{"keyword":"停車場很大","category":"env"},{"keyword":"洗手間乾淨","category":"env"},{"keyword":"香火鼎盛不嗆鼻","category":"env"},{"keyword":"動線規劃好","category":"env"},{"keyword":"古色古香","category":"env"},{"keyword":"庭園造景優美","category":"env"},{"keyword":"夜間燈光莊嚴","category":"env"},{"keyword":"廟埕空間寬敞","category":"env"},{"keyword":"周邊小吃豐富","category":"env"},{"keyword":"交通便利好找","category":"env"},
  {"keyword":"收費透明","category":"price"},{"keyword":"點燈費用合理","category":"price"},{"keyword":"隨喜功德自由","category":"price"},{"keyword":"安太歲費公道","category":"price"},{"keyword":"法會費用透明","category":"price"},{"keyword":"金紙種類齊全","category":"price"},{"keyword":"不強迫添油香","category":"price"},{"keyword":"光明燈價格親民","category":"price"},{"keyword":"每年法會必參加","category":"price"},{"keyword":"心靈寄託中心","category":"price"},{"keyword":"拜完心情變好","category":"price"},{"keyword":"在地信仰依靠","category":"price"}
]'::jsonb, 5, true),
('association', '社團法人/協會', '🤝', '[
  {"keyword":"辦訓課程專業","category":"service"},{"keyword":"對接資源快速","category":"service"},{"keyword":"法律諮詢到位","category":"service"},{"keyword":"會務處理細心","category":"service"},{"keyword":"專家經驗豐富","category":"service"},{"keyword":"資料整理齊全","category":"service"},{"keyword":"服務效率極高","category":"service"},{"keyword":"提供實質幫助","category":"service"},{"keyword":"回覆速度很快","category":"service"},{"keyword":"行政作業順暢","category":"service"},{"keyword":"理事長很親民","category":"service"},{"keyword":"秘書處很用心","category":"service"},
  {"keyword":"入會受益匪淺","category":"tech"},{"keyword":"認識優秀夥伴","category":"tech"},{"keyword":"真正有在做事","category":"tech"},{"keyword":"產業資訊豐富","category":"tech"},{"keyword":"課程內容紮實","category":"tech"},{"keyword":"講師陣容堅強","category":"tech"},{"keyword":"輔導計畫完善","category":"tech"},{"keyword":"媒合機會多","category":"tech"},{"keyword":"認證制度公正","category":"tech"},{"keyword":"政策倡議有力","category":"tech"},{"keyword":"研討會品質高","category":"tech"},{"keyword":"跨業交流廣泛","category":"tech"},
  {"keyword":"活動空間寬敞","category":"env"},{"keyword":"教室設備先進","category":"env"},{"keyword":"交通便利好找","category":"env"},{"keyword":"環境整潔舒適","category":"env"},{"keyword":"線上系統好用","category":"env"},{"keyword":"會議室設備齊全","category":"env"},{"keyword":"報名流程簡便","category":"env"},{"keyword":"場地燈光舒適","category":"env"},{"keyword":"茶水供應充足","category":"env"},{"keyword":"簽到系統便捷","category":"env"},{"keyword":"停車空間足夠","category":"env"},{"keyword":"無障礙設施完善","category":"env"},
  {"keyword":"經費運用透明","category":"price"},{"keyword":"會費合理值得","category":"price"},{"keyword":"課程費用公道","category":"price"},{"keyword":"年費性價比高","category":"price"},{"keyword":"財務報告公開","category":"price"},{"keyword":"補助申請順利","category":"price"},{"keyword":"活動費用合理","category":"price"},{"keyword":"推薦同業加入","category":"price"},{"keyword":"像一個大家庭","category":"price"},{"keyword":"感受到溫暖","category":"price"},{"keyword":"很有歸屬感","category":"price"},{"keyword":"收費說明清楚","category":"price"}
]'::jsonb, 6, true)
ON CONFLICT (template_id) DO UPDATE SET label=EXCLUDED.label, emoji=EXCLUDED.emoji, keywords=EXCLUDED.keywords, sort_order=EXCLUDED.sort_order, is_active=EXCLUDED.is_active, updated_at=now();